#!/usr/bin/env python3
from __future__ import annotations
import argparse
from pathlib import Path
from loclib import *

def c_bytes(s: str) -> str:
    # ASCII-only C literal. Use octal escapes to avoid \x hex-run ambiguity.
    b=s.encode('utf-8')
    out=[]
    for x in b:
        if x==0x22: out.append('\\"')
        elif x==0x5c: out.append('\\\\')
        elif x==0x0a: out.append('\\n')
        elif x==0x0d: out.append('\\r')
        elif x==0x09: out.append('\\t')
        elif 0x20 <= x < 0x7f: out.append(chr(x))
        else: out.append(f'\\{x:03o}')
    return ''.join(out)

def render_header(catalog: dict, zh: dict) -> str:
    z=zh.get('entries',{}); rows=[]
    for k,e in catalog.get('entries',{}).items():
        if e.get('obsolete'): continue
        tr=z.get(k,{})
        text=''
        state=tr.get('state','missing')
        if tr.get('source_hash')==e.get('source_hash') and state in ('reviewed','machine_translated'):
            text=tr.get('text','')
        rows.append((k,e.get('source',''),text,state))
    rows.sort(key=lambda r:r[0])
    lines=['// Generated by tools/generate_cpp.py. DO NOT EDIT.','#pragma once','#include <cstddef>','namespace OptiScalerCN::Generated {','struct TranslationEntry { const char* key; const char* source; const char* zh; };','inline constexpr TranslationEntry kTranslations[] = {']
    for k,s,t,state in rows:
        lines.append(f'    {{"{c_bytes(k)}", "{c_bytes(s)}", "{c_bytes(t)}"}}, // {state}')
    lines += ['};','inline constexpr std::size_t kTranslationCount = sizeof(kTranslations) / sizeof(kTranslations[0]);','} // namespace OptiScalerCN::Generated','']
    return '\n'.join(lines)

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--out',type=Path,required=True); ap.add_argument('--channel',choices=CHANNELS,default='master'); args=ap.parse_args()
    paths=localization_channel_paths(args.channel)
    cat=load_json(paths['catalog'],{}); zh=load_json(LOC/'zh-CN.json',{})
    rendered=render_header(cat, zh)
    args.out.parent.mkdir(parents=True,exist_ok=True); args.out.write_text(rendered,encoding='ascii')
    count=sum(1 for e in cat.get('entries',{}).values() if not e.get('obsolete'))
    print(f'generated {count} entries -> {args.out}')
if __name__=='__main__': main()
